### PR TITLE
bug fixed validation on props

### LINKED ISSUE #292: Cannot use `address` prop.
I think this was maybe introduced very recently, could have been a merge conflict gone wrong or what, I'm not sure, but Im trying to use this

```js
showLocation({
    address: 'some address here'
})
```

However it is throwing the following error:

```
 ERROR  [MapsException: `showLocation` should contain keys `latitude` and `longitude`.]
```

When digging into the source code and the `checkOptions` function, the first check is for lat/lon - I think there is a left over condition here? e.g. should `if (!latitude || !longitude) {` have been removed, which would allow the lat/lon/address check to kick in? Additionally should the `if (address && typeof address !== 'string') {` check come after the lat/lon/address check?

```js
const checkOptions = ({ latitude, longitude, address, googleForceLatLon, googlePlaceId, title, app, prefixes, appTitles, appsWhiteList, }) => {
    if (!latitude || !longitude) {
        throw new MapsException('`showLocation` should contain keys `latitude` and `longitude`.');
    }
    if (address && typeof address !== 'string') {
        throw new MapsException('Option `address` should be of type `string`.');
    }
    if (!latitude && !longitude && !address) {
        throw new MapsException('`latitude` & `longitude` or `address` is required. Both cannot be undefined.');
    }
```

Thanks!

### PR DESCRIPTION
**Pull request by OwenMelbz**
Fixes #292

### CODE REVIEW

**Comment by tschoffelen** [comment]
Sorry for missing this one! Thanks for submitting!!

File: src/utils.ts [hunk 1]
```diff
@@ -186,19 +186,14 @@ export const checkOptions = ({
   prefixes: Record<string, string>;
   appsWhiteList: string[] | null | undefined;
 }): void => {
-  if (!latitude || !longitude) {
+  if ((!latitude && !longitude) || !address) {
```
Comment (tschoffelen) [inline src/utils.ts:189]: suggestion: I think this logic might still not be exactly right - this will currently trigger the exception for every case where lat/lng + address aren't both supplied. I think it should be this:

```suggestion
  if (!(latitude && longitude) && !address) {
```

**Comment by alban-ameti** [comment]
Any news on merging this?

**Review by tschoffelen — APPROVED** [review]
