### PR TITLE
fix: issue 223 - improve TS support, fix bug in getApps generateTitles

### LINKED ISSUE #223: not showing location in search bar google map
<strong>Hi!</strong>
I open google map with iphone and the location on input is not displayed, for android it is displayed normally
anyone like me?
image
<br />
image

### LINKED ISSUE #233: Improved TS support, fix appTitles bug in getApps
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-map-link@2.10.0` for the project I'm working on.

Here is the diff that solved my problem: I will open up a PR for this if you feel its valuable.

```diff
diff --git a/node_modules/react-native-map-link/index.d.ts b/node_modules/react-native-map-link/index.d.ts
index 76e1fa2..12baa8b 100644
--- a/node_modules/react-native-map-link/index.d.ts
+++ b/node_modules/react-native-map-link/index.d.ts
@@ -10,12 +10,12 @@ interface Options {
   googleForceLatLon?: boolean;
   googlePlaceId?: string;
   title?: string;
-  app?: string;
+  app?: MapId;
   dialogTitle?: string;
   dialogMessage?: string;
   cancelText?: string;
-  appsWhiteList?: string[];
-  appTitles?: {[key: string]: string};
+  appsWhiteList?: MapId[];
+  appTitles?: Partial<Record<MapId, string>>;
   naverCallerName?: string;
   directionsMode?: 'car' | 'walk' | 'public-transport' | 'bike';
 }
@@ -45,8 +45,8 @@ interface PopupProps {
   style?: PopupStyleProp;
   modalProps?: object;
   options: Options;
-  appsWhiteList?: string[];
-  appTitles?: {[key: string]: string};
+  appsWhiteList?: MapId[];
+  appTitles?: Partial<Record<MapId, string>>;
 }
 
 export function showLocation(
@@ -54,10 +54,10 @@ export function showLocation(
 ): Promise<string | undefined | null>;
 
 
-export type GetAppResult = {id:string, name: string, icon: ImageSourcePropType, open: () => Promise<void>}
+export type GetAppResult = {id: MapId, name: string, icon: ImageSourcePropType, open: () => Promise<void>}
 export function getApps(
   options: Options,
-  select?:string[]
-): Promise<GetAppsResult[]>;
+): Promise<GetAppResult[]>;
 
 export class Popup extends React.Component<PopupProps> {}
+export type MapId = 'apple-maps' | 'google-maps' | 'citymapper' | 'uber' | 'lyft' | 'transit' | 'truckmap' | 'waze' | 'yandex' | 'moovit' | 'yandex-maps' | 'yandex-taxi' | 'kakaomap' | 'mapycz' | 'maps-me' | 'osmand' | 'gett' | 'navermap' | 'dgis' | 'liftago' | 'petalmaps'
diff --git a/node_modules/react-native-map-link/src/index.js b/node_modules/react-native-map-link/src/index.js
index d26de4d..e839054 100644
--- a/node_modules/react-native-map-link/src/index.js
+++ b/node_modules/react-native-map-link/src/index.js
@@ -312,7 +312,7 @@ export async function getApps(options) {
     apps = apps.filter((appName) => options.appsWhiteList.includes(appName));
   }
 
-  const titles = generateTitles();
+  const titles = generateTitles(options.appTitles);
   async function open(app) {
     return showLocation({...options, app});
   }
```

To build on top of #232, this adds better TS support so consumers can compose their own mappings for titles, icons, etc.
Screen Shot 2022-07-26 at 9 32 05 PM

It also adds better typing support for things like `appTitles` for a better dev XP.
Screen Shot 2022-07-26 at 9 38 26 PM

It also fixes a bug with `getApps` not passing down `options.appTitles`

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

### PR DESCRIPTION
**Pull request by ChrisLFieldsII**
fixes #233 

- improves TS support so other TS consumers can compose their own types
- improves JSDocs. Hovering over certain functions/variables shows description
- fixes bug in `getApps` not passing down `options.appTitles`

Screen Shot 2022-07-27 at 12 34 43 PM

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -2,11 +2,7 @@
  * React Native Map Link
  */
 
-import Popup from './src/components/Popup'
-import { showLocation, getApps } from './src'
+import Popup from './src/components/Popup';
```
Comment (ChrisLFieldsII) [inline index.js:5]: the changes in this file were just applying linting

**Review by tschoffelen — APPROVED** [review]

**Comment by tschoffelen** [comment]
Thanks, this is really helpful!

Released as `react-native-map-link@2.10.1`

**Comment by ChrisLFieldsII** [comment]
> Thanks, this is really helpful!
> 
> Released as `react-native-map-link@2.10.1`

Awesome, thanks for the release!
